name: Build Optimized Main APK

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - alpha

permissions:
  contents: write

jobs:
  build-and-artifact:
    name: Build and Upload Artifact
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Make Gradle Wrapper Executable
        run: chmod +x ./gradlew

      - name: Build Minified Release APK
        # Skipping tests and lint to save RAM during the build process
        run: ./gradlew assembleRelease --no-daemon -x test -x lint

      - name: Upload APK to Actions Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: VoxSherpa-Main-APK
          path: app/build/outputs/apk/release/*.apk
          retention-days: 5
